### ISSUE TITLE
Little question about the UI icons

### ISSUE THREAD

**Issue by FarSightHunter** [kinmury/obsidian-ukiyo#5] opened 2022-11-06 01:09 UTC
This is the most amazing theme I've encountered so far, smooth and comfortable, except for a few (though not too much) UI hiccups, I was wondering if you guys are also experiencing these issues, or do you have any solutions? Thank you very much
1. **the “Expand” and“Open quick switcher”icons overslap**
![HOZTUK8~9OVIJ RVRXQD}Q6](https://user-images.githubusercontent.com/84265227/200149280-ca951b6b-560c-4f50-a801-5540fdb3227d.png)
2. **half of the "Setting" icons is covered by edge**
![RSIBJTESO9C8Z%MYE32YC9F](https://user-images.githubusercontent.com/84265227/200149297-4b124c1f-abfb-4924-acf0-9b707925a3ef.png)
3. **little of the "File" icon is coverd by edge**
![J~P57(6G0DA U(DU$8)H5Z0](https://user-images.githubusercontent.com/84265227/200149304-6e19e5ab-8b65-4783-b61f-533eeafc69c0.png)
my obsidian version is v.1.0.3,and my Ukiyo(legacy) version is v1.0.37.
Thanks again

**Comment by kinmury** [comment] 2022-11-07 09:10
Yeah the issue is that you're using the legacy version, not the beta one. If you see the GitHub releases, you'll see that the "last one" is the one that you are using, but the actual last version is the one that is in beta (that you can also see on the release page). 

But I suggest that you go to the Community Themes Panel inside Obsidian, and reinstall the theme from there. You should be able to use the newest version.

I'll close this issue (if there is no more trouble about this, obviously) since it's not related to the latest version.

I'm glad that you like it, and hope that you can enjoy the newest version. 😃

**Closed** 2022-11-12 17:01 UTC
